---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1
    driver:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[fanatics_pipeline::default]
    attributes:
